### PR TITLE
Fix unread line after menu, parser_end after menu

### PR DESCRIPTION
**Pull request by theludovyc**
Review me 🥳

### CODE REVIEW

**Comment by Jeremi360** [comment]
@theludovyc So after this indent should work right, but only in menus ?

**Comment by theludovyc** [comment]
## unread line after menu
**Exemple**
```
menu:
  choice_a > jump bla
  choice_b
bla:
  "something happen"
```

**Before fix**
When you choose choice_a parser reach end without jump on bla. Beacause it is in jump mode and search "bla:". But it start searching with "something happen". Why ? End of choices are detected by indent == 0, and we have it when parser read line "bla:", and it is in Menu mode. After it is send signal choices and wait return. We are there https://github.com/rakugoteam/Rakugo/blob/1fa078a4907cf6da3327a0d8c9c2399996ff824c/addons/Rakugo/lib/systems/Parser.gd#L285. Choice is choice_a so we want to jump. But label "bla" has never read. So parser go to jump mode. We quit if statement and reach continue there https://github.com/rakugoteam/Rakugo/blob/1fa078a4907cf6da3327a0d8c9c2399996ff824c/addons/Rakugo/lib/systems/Parser.gd#L296. So new loop, new line read "something happen". "bla:" is never parse.

**How I fix it**
I move indent == 0 test on Menu Mode before match https://github.com/rakugoteam/Rakugo/pull/45/files#diff-c4b0488a528780b1bc81202aeda06c033ee8dddb9e684efed03703c979d62742R207 and remove older https://github.com/rakugoteam/Rakugo/pull/45/files#diff-c4b0488a528780b1bc81202aeda06c033ee8dddb9e684efed03703c979d62742L273.
In this case we can be in Jump state without have new line read.

## parser_end after menu
**Exemple**
```
menu:
  choice_a > jump bla
  choice_b <= end of file
```

**Before fix**
When end of file is not on new line, parser don't send signal menu. It is because of the shape of the while there https://github.com/rakugoteam/Rakugo/blob/1fa078a4907cf6da3327a0d8c9c2399996ff824c/addons/Rakugo/lib/systems/Parser.gd#L168. We have "and !file.eof_reached()". And we reached it after https://github.com/rakugoteam/Rakugo/blob/1fa078a4907cf6da3327a0d8c9c2399996ff824c/addons/Rakugo/lib/systems/Parser.gd#L310.

**How I fix it**
I had new test https://github.com/rakugoteam/Rakugo/pull/45/files#diff-c4b0488a528780b1bc81202aeda06c033ee8dddb9e684efed03703c979d62742R168. So if end of file is reached and we are in menu mode, Signal("menu") is send.

## Code is ugly
You can see things repeated. And we gonna do this for Aks I thing. That why I wrote https://github.com/rakugoteam/Rakugo/pull/45/files#diff-c4b0488a528780b1bc81202aeda06c033ee8dddb9e684efed03703c979d62742R149. I wouldn't go any further without changing the architecture. I just fix it faster to use it with my old project. It works. But I can do better. You can merge it. It's dramatic if we don't change it. But don't worry I can't leave it like that !

**Comment by Jeremi360** [comment]
@theludovyc I see, but in your answer you give me to *Before fix* and only  one *How I fix it* described as *WIP*.
So now I'm confused if this is fixed or not.

**Comment by Jeremi360** [comment]
@theludovyc I see, but give me to *Before fix* and only  one *How I fix it* described as *WIP*.
So now I'm confused if this is fixed or not.

**Review by Jeremi360 — APPROVED** [review]

**Pull request merged**
