### PR TITLE
fix #242 add full doc example

### LINKED ISSUE #242: Add the full example from the doc
Curently  we are not tested the full example in the doc https://rakugoteam.github.io/rakugo-docs/2.1/rakugo_singleton/#full-exemple

### PR DESCRIPTION
**Pull request by theludovyc**
fix #242

### CODE REVIEW

**Comment by Jeremi360** [comment]
Maybe as this is our official docs example should set it as Project start scene ?

**Comment by Jeremi360** [comment]
@theludovyc
Maybe as this is our official docs example should set it as Project start scene ?

**Comment by theludovyc** [comment]
> Maybe as this is our official docs example should set it as Project start scene ? 

Normally instead of devs, people not use the rakugo project 😊

**Comment by Jeremi360** [comment]
> Normally instead of devs, people not use the rakugo project 😊

@theludovyc, I know, I know, but it feels litte unreving when this start scene is null in godot project.

**Comment by theludovyc** [comment]
> I know, I know, but it feels litte unreving when this start scene is null in godot project.

I see what you mean. Maybe you can do an issue "My second fixies for 2.1.1" ? 😁

**Pull request merged**
