### PR TITLE
Fix #209

### LINKED ISSUE #209: We can define var in middle of the line
We have now 
```gdscript
SET_VARIABLE = "(?<lvar_name>{VARIABLE}) = ((?<text>{STRING})|(?<number>{NUMERIC})|(?<rvar_name>{VARIABLE}))"
```
Is doesn't start with `^` and doesn't ends with `$` so we can do:
`some x = 5 abc` with no errors and ti give us var `x = 5`, but it should give us an error.
It should be possible only as `x = 5`.

### PR DESCRIPTION
**Pull request by Jeremi360**
Added `^` at start and `$` at end to `SET_VARIABLE`

### CODE REVIEW

**Comment by theludovyc** [comment]
fix #209

**Comment by theludovyc** [comment]
image

Why you have this strange commit here ?

**Comment by Jeremi360** [comment]
> image
> 
> Why you have this strange commit here ?

So @theludovyc  I just had my repo branches out of sync with with main repo and this fixing that, 
so it will not  influence main repo after PR Merge

**Comment by theludovyc** [comment]
Okay got it 👌

**Review by theludovyc — APPROVED** [review]

**Pull request merged**
