### PR TITLE
add variable_changed signal

### PR DESCRIPTION
**Pull request by Jeremi360**
This signal is emitted when `set_variable()` is called.
This signal pass to connected func `variable_name` and its  `new_value`.

### CODE REVIEW

**Comment by theludovyc** [comment]
Hello @Jeremi360 :) !

You have a merge commit, this is bad. You should delete it, or make a new branch and cherry pick.

Also, I see you add signal in set_variable but not in set_character_variable. Is this on purpose ?

**Comment by Jeremi360** [comment]
@theludovyc sorry I didn't saw your comment at first only that you give it a label.
Why having merge commit is bad ?
> Also, I see you add signal in set_variable but not in set_character_variable. Is this on purpose ?

It was on purpose I for some reason I was sure that `set_character_variable()` calls `set_variable()` my bad.
I will try to revert this PR merge as soon as possible.

**Comment by Jeremi360** [comment]
@theludovyc Reverted with #162 , but it don't make it open again :/ so I will need to make new PR.

**Comment by theludovyc** [comment]
> Why having merge commit is bad ?

@Jeremi360 because you add it with all it contains. So you can have bad surprises ^^

> so I will need to make new PR.

Wait new one :)

**Pull request merged**
